name: alarm_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.4+5
  tflite: ^1.1.2
  file_picker: ^4.0.0
  flutter_local_notifications: ^9.0.0
  timezone: ^0.8.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/ringtones/
